### ISSUE TITLE
Data Ingestion outside of the US

### ISSUE THREAD

**Issue by mowoe** [shlomikushchi/zipline-trader#163]
I cant seem to be able to ingest data which didnt come from the alpaca api, which is only availible for us citizens. Is there any way to get the quandl ingestion working? I had to modify the `quandl.py` by removing the relative imports, but still im not able to ingest any data. I know @shlomikushchi alraidy stated in #142 that there is currently only the alpaca api supported, has thisby any chance changed now or will it ever change? I would submit a PR, but atm im not able to get the quandl ingestion working...

**Comment by shlomikushchi** [comment]
Hi,  alpaca data is available for all. live accounts are available to US citizens and requires special approval outside us. 
quandl is not free data. the free bundle doesn't work anymore since they stopped providing it. 
we are already working on a bundle for alpha vantage free api (https://github.com/shlomikushchi/zipline-trader/pull/155)
and may do more in the future.
the goal is to support free data sources, so everyone could use it. quandl isn't free

**Comment by mowoe** [comment]
Thank you so much, i was a bit lost in the alpaca UI and didnt realize you had to change to paper trading...
